#!/usr/bin/env node
'use strict'

const { uploadData } = require('asclepios-sse-client');
const { execFile } = require('child_process');

const {
    XNAT_USER,
    XNAT_PASS,
    XNAT_HOST,
    SSE_CLIENT_SSE_SERVER_URL,
    SSE_CLIENT_TA_URL,
    SSE_CLIENT_KEY_G,
    SSE_CLIENT_KENC,
    SSE_CLIENT_SALT_VALUE,
    SSE_CLIENT_IV_VALUE
} = process.env;

if (!(XNAT_USER && XNAT_PASS && XNAT_HOST && SSE_CLIENT_SSE_SERVER_URL && SSE_CLIENT_KEY_G && SSE_CLIENT_KENC && SSE_CLIENT_TA_URL && SSE_CLIENT_SALT_VALUE && SSE_CLIENT_IV_VALUE)) {
    throw 'One or more of the following environment variables not set: ' +
        'XNAT_USER, XNAT_PASS, XNAT_HOST, SSE_CLIENT_SSE_SERVER_URL, SSE_CLIENT_KEY_G, SSE_CLIENT_KENC, SSE_CLIENT_TA_URL, SSE_CLIENT_SALT_VALUE, SSE_CLIENT_IV_VALUE';
}

const XnatDataClient = '/usr/bin/XnatDataClient'
const path = process.argv[2]
const args = ['-u', XNAT_USER, '-p', XNAT_PASS, '-r', `${XNAT_HOST}/REST${path}?format=json`];

execFile(XnatDataClient, args, function callback(error, stdout, stderr) {
    if (error) {
        console.error(stderr);
        throw error;
    }

    const response = JSON.parse(stdout);

    const ID = response.items[0].data_fields.ID
    const label = response.items[0].data_fields.label
    const data = response.items[0].children[0].items[0].data_fields;

    data['ID'] = ID;
    data['label'] = label;

    uploadData(data, ID, SSE_CLIENT_KEY_G, SSE_CLIENT_KENC);
});
