#!/usr/bin/env bash

set -eu

IMAGE=docker.io/somnonetz/pn-tds-biosignals2csv:dev

docker build --pull -t ${IMAGE} .
docker run --rm -u 1000:1000 ${IMAGE} red-connector-ssh --version
docker run --rm -u 1000:1000 ${IMAGE} red-connector-http --version
docker run --rm -u 1000:1000 ${IMAGE} red-connector-xnat-http --version
docker push ${IMAGE}
