#!/usr/bin/env python3

import os
from argparse import ArgumentParser
from subprocess import call
import tempfile
import shutil

parser = ArgumentParser(description='Search for query terms in text files.')
parser.add_argument(
   'data', action='store', type=str, metavar='FILE'
)
parser.add_argument(
   '--montage', action='store', type=str, metavar='FILE'
)
parser.add_argument(
   '--headers', action='store', type=str, metavar='FILE'
)

args = parser.parse_args()

mcr_root = os.environ['MCR_ROOT']
inputs_dir = tempfile.mkdtemp()

mv_data = os.path.join(inputs_dir, 'data.mat')
os.symlink(args.data, mv_data)

command = 'run_pn_tds_biosignals2csv.sh {} data {}'.format(mcr_root, mv_data)

if args.montage is not None:
    mv_montage = os.path.join(inputs_dir, 'montage.txt')
    os.symlink(args.montage, mv_montage)
    command = '{} montage {}'.format(command, mv_montage)

if args.headers is not None:
    mv_headers = os.path.join(inputs_dir, 'headers.mat')
    os.symlink(args.headers, mv_headers)
    command = '{} headers {}'.format(command, mv_headers)

return_code = call(command, shell=True)
shutil.rmtree(inputs_dir)
exit(return_code)

